version: '3.8'

services:
  app:
    build: .
    container_name: elevio_app
    restart: always
    ports:
      - "${PORT}:5000"
  
  nginx:
    image: nginx:alpine
    container_name: elevio_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app